# Generated by Django 5.2.1 on 2025-05-20 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Basement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_list', models.JSONField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_list', models.JSONField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='F1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_list', models.JSONField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='F2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_list', models.JSONField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_list', models.JSONField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.checklist')),
            ],
        ),
    ]
